### ISSUE TITLE
research what meta data can/should be attached to each NFT

### ISSUE THREAD

**Issue by normadn** [frens-pool/frens-contracts#2]

**Comment by 0xWildhare** [comment]
the portion of the NFT contract that will generate the metadata will be broken out into its own contract, which will be upgradable. This makes it so that all of these questions do not need to be answered upfront (as we can add more later). currently the metadata includes:

pool address
pool status (staked, awaiting deposits etc)
validator public key (proud of this it was a pain in the ass)
eth stake represented by the NFT
claimable rewards for the NFT
operator IDs of SSV operators for that pool (if selected)
